import { test, expect, type Page } from '@playwright/test'

// Covers the app's core, novel path: a fully client-side encrypted vault with
// no server-side account concept. Deliberately doesn't require the backend to
// be reachable — account-detail page balance fetches are allowed to fail
// (caught and toasted, not asserted on here) since that's provider/API-key
// dependent and orthogonal to what this test verifies.

// The real quick-unlock method (a WebAuthn passkey) can't be driven through a
// headless browser without a virtual authenticator, so these tests
// deliberately skip setup — exercising the recovery-phrase-only path, which
// the app must always support as documented in the skip-warning dialog.
// The recovery phrase is generated by the app itself (a random 24-word BIP-39
// mnemonic, not something the user types in), so it's scraped off the page
// rather than hardcoded.
async function createVaultSkippingQuickUnlock(page: Page): Promise<string> {
  const words = await page.getByTestId('recovery-phrase-word').allTextContents()
  const recoveryPhrase = words.join(' ')

  await page.getByLabel("I've saved my recovery phrase somewhere safe").check()
  await page.getByRole('button', { name: 'Create vault' }).click()

  await expect(page.getByRole('button', { name: 'Done' })).toBeVisible()
  await page.getByRole('button', { name: 'Done' }).click()

  // No passkey was set up — confirm the skip-warning dialog.
  await expect(page.getByRole('button', { name: 'Continue anyway' })).toBeVisible()
  await page.getByRole('button', { name: 'Continue anyway' }).click()
  await expect(page).toHaveURL(/\/$/)

  return recoveryPhrase
}

async function addAccount(page: Page, label: string) {
  await page.getByRole('link', { name: 'Add account' }).click()
  await expect(page).toHaveURL(/\/accounts\/new$/)

  await page.getByRole('textbox', { name: 'Label' }).fill(label)
  await page.getByRole('button', { name: 'Add account' }).click()

  await expect(page).toHaveURL(/\/$/)
}

test('create a vault, add a wallet, and confirm it survives a reload', async ({ page }) => {
  await page.goto('/')
  await expect(page).toHaveURL(/\/vault\/setup$/)

  const recoveryPhrase = await createVaultSkippingQuickUnlock(page)

  await addAccount(page, 'E2E Test Wallet')
  await expect(page.getByText('E2E Test Wallet')).toBeVisible()

  // Reload: the vault must lock (session key is memory-only) and require the recovery phrase again.
  await page.reload()
  await expect(page).toHaveURL(/\/vault\/unlock$/)

  await page.getByRole('textbox', { name: 'Recovery phrase (24 words)' }).fill(recoveryPhrase)
  await page.getByRole('button', { name: 'Unlock' }).click()

  await expect(page).toHaveURL(/\/$/)
  await expect(page.getByText('E2E Test Wallet')).toBeVisible()
})

test('rejects the wrong recovery phrase on unlock', async ({ page }) => {
  await page.goto('/')
  await createVaultSkippingQuickUnlock(page)

  await page.reload()
  await expect(page).toHaveURL(/\/vault\/unlock$/)

  await page
    .getByRole('textbox', { name: 'Recovery phrase (24 words)' })
    .fill('definitely the wrong recovery phrase words here')
  await page.getByRole('button', { name: 'Unlock' }).click()

  // Still locked — the wrong recovery phrase must not unlock the vault.
  await expect(page).toHaveURL(/\/vault\/unlock$/)
})

// The app has no per-account detail page anymore — Send/Receive/Transactions
// are all reachable straight from the account card on the persistent
// Accounts screen (App.vue keeps AccountsView mounted and layers other
// routes over it in a floating PaneOverlay instead of navigating away from
// it), and Swap lives as a second tab inside the same Send panel rather than
// its own destination.
test('account card exposes send, receive, and transactions actions', async ({ page }) => {
  await page.goto('/')
  await createVaultSkippingQuickUnlock(page)
  await addAccount(page, 'E2E Test Wallet')

  // Both routes render inside the same floating PaneOverlay, which has its
  // own "Close" button — scoped to it since the persistent settings gear
  // behind it (App.vue) has an unrelated, similarly-named "Close settings" button.
  const pane = page.locator('.pane-card')

  await page.getByRole('button', { name: /^Send/ }).click()
  await expect(page).toHaveURL(/\/send$/)
  await expect(page.getByRole('heading', { name: 'Send', level: 1 })).toBeVisible()
  await expect(page.getByRole('tab', { name: 'Swap' })).toBeVisible()
  await pane.getByRole('button', { name: 'Close' }).click()
  await expect(page).toHaveURL(/\/$/)

  await page.getByRole('button', { name: 'View QR code' }).click()
  await expect(page).toHaveURL(/\/receive$/)
  await expect(page.getByRole('heading', { name: 'Receive', level: 1 })).toBeVisible()
  await pane.getByRole('button', { name: 'Close' }).click()
  await expect(page).toHaveURL(/\/$/)

  // Transactions expand inline on the card itself rather than navigating
  // anywhere — the row toggling this has no accessible name of its own
  // (only its chevron icon does), so it's targeted by its structural class.
  await page.locator('.balance-row').first().click()
  await expect(page.getByText('No transactions found.')).toBeVisible()
})
